- name: Instalacja paczek unzip/ net-tools
  hosts: local
  connection: local
  become: true

  tasks:
    - name: Instalacja paczek unzip/ net-tools
      package:
        name: 
        - unzip
        - net-tools
        state: present